server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

    backoff_config:
      min_period:  500ms
      max_period:  5m
      max_retries: 10

    batchsize:  1048576   # 1 MB
    batchwait:  1s

scrape_configs:

  - job_name: spring-logs

    static_configs:
      - targets:
          - localhost

        labels:
          job:         spring
          host:        docker
          application: inspectflow
          environment: production
          __path__:    /logs/*.log

    pipeline_stages:

      - json:
          expressions:
            level:       level
            traceId:     traceId
            spanId:      spanId
            logger_name: logger_name
            message:     message

      - labels:
          level:       level
          traceId:     traceId

      - match:
          selector: '{job="spring"} |= ""'
          stages:
            - drop:
                expression: '"level":"(DEBUG|TRACE)"'
