spring:
  flyway:
    locations: classpath:db/migration/dev

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.opentelemetry.exporter: DEBUG
    net.ttddyy.observation: DEBUG


app:
  security:
    jwt:
      issuer: http://localhost:4200
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:false}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:None}

  bucket:
    minio:
      bucketName: inspectflow
      endpoint: http://localhost:9000
      access-key: admin
      secret-key: admin123
      public-url: http://localhost:9000

  host:
    api: "http://localhost:8080"
    web: "http://localhost:4200"

springdoc:
  api-docs:
    enabled: true

scalar:
  enabled: true

