logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  security:
    jwt:
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:false}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:None}