spring:
  application:
    name: inspectflow

  profiles:
    active: ${SPRING_PROFILE:dev}


  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inspectflow}?createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  flyway:
    enabled: true
    baseline-on-migrate: true


app:
  security:
    jwt:
      expiration: ${JWT_EXPIRATION:86400000}  # 24 hours
      cookie-name: ${JWT_COOKIE_NAME:auth-token}
      cookie-secure: ${COOKIE_SECURE:false}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:Strict}
      private-key-path: "classpath:keys/private.pem"
      public-key-path: "classpath:keys/public.pem"

  data:
    mongodb:
      uri: mongodb://admin:admin_pass@127.0.0.1:27017/inspectflow?authSource=admin
      database: inspectflow

  bucket:
    minio:
      bucketName: inspectflow
      endpoint: http://localhost:9000
      access-key: admin
      secret-key: admin123