spring:
  application:
    name: inspectflow

  threads:
    virtual:
      enabled: true

  profiles:
    active: ${SPRING_PROFILE:dev}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inspectflow}?createDatabaseIfNotExist=true
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    properties:
      hibernate:
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    from: "InspectFlow <noreply@inspectflow.com.br>"
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  security:
    jwt:
      issuer: http://localhost:8080
      expiration: ${JWT_EXPIRATION:86400000}  # 24 hours
      cookie-name: ${JWT_COOKIE_NAME:auth-token}
      cookie-secure: ${COOKIE_SECURE:false}
      cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
      cookie-same-site: ${JWT_COOKIE_SAME_SITE:Strict}
      private-key-path: "classpath:keys/private.pem"
      public-key-path: "classpath:keys/public.pem"

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:admin_pass@127.0.0.1:27017/inspectflow?authSource=admin }
      database: inspectflow

  bucket:
    minio:
      bucketName: ${MINIO_BUCKET_NAME:inspectflow}
      endpoint: ${MINIO_ENDPOINT:http://minio:9000}
      access-key: ${MINIO_ACCESS_KEY:admin}
      secret-key: ${MINIO_SECRET_KEY:admin123}
      public-url: ${MINIO_PUBLIC_URL:https://minio.rflgx.com.br}

  host:
    api: "http://localhost:8080"
    web: "https://inspectflow.rflgx.com.br"


springdoc:
  api-docs:
    enabled: false

scalar:
  enabled: false